version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mongo:4.4.6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db